services:
  backend:
    build: ./app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app
    environment:
      - PYTHONPATH=/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    command: npm start