services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=.
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"