services:
  postgres:
    build: .
    container_name: postgres-db
    environment:
      POSTGRES_USER: suyashghimire
      POSTGRES_PASSWORD: root
      POSTGRES_DB: local
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./pg_backup.sql:/docker-entrypoint-initdb.d/pg_backup.sql
    networks:
      - my-app-network

volumes:
  postgres-data:

networks:
  my-app-network:
    external: true